import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface ReportHeader {
  institutionName: string;
  reportTitle: string;
  generatedBy: string;
  departmentLabel?: string;
  generatedDate?: string;
  generatedTime?: string;
}

export function createPDF(header: ReportHeader): jsPDF {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;

  // Top dark-blue banner
  doc.setFillColor(15, 37, 87);
  doc.rect(0, 0, pageWidth, 32, "F");

  // College name (white, bold, centered)
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(header.institutionName, pageWidth / 2, 13, { align: "center" });

  // Sub-tagline
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("Information Management System \u2014 Faculty Portal", pageWidth / 2, 20, { align: "center" });

  // Generated date (right-aligned small text)
  if (header.generatedDate) {
    doc.setFontSize(7);
    const dateLine = header.generatedTime
      ? header.generatedDate + "  " + header.generatedTime
      : header.generatedDate;
    doc.text(dateLine, pageWidth - margin, 27, { align: "right" });
  }

  // Gold accent line
  doc.setDrawColor(232, 160, 32);
  doc.setLineWidth(1.2);
  doc.line(0, 32, pageWidth, 32);

  // Report title below banner
  doc.setTextColor(15, 37, 87);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(header.reportTitle, pageWidth / 2, 43, { align: "center" });

  if (header.departmentLabel) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(107, 114, 128);
    doc.text(header.departmentLabel, pageWidth / 2, 50, { align: "center" });
  }

  // Separator line
  doc.setDrawColor(229, 231, 235);
  doc.setLineWidth(0.4);
  doc.line(margin, 55, pageWidth - margin, 55);

  doc.setTextColor(0, 0, 0);
  return doc;
}

export function addPageNumbers(doc: jsPDF): void {
  const pageCount = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(107, 114, 128);
    doc.text(
      `Page ${i} of ${pageCount}  |  Generated by IMS Portal`,
      pageWidth / 2,
      pageHeight - 8,
      { align: "center" }
    );
    doc.setDrawColor(229, 231, 235);
    doc.setLineWidth(0.3);
    doc.line(15, pageHeight - 12, pageWidth - 15, pageHeight - 12);
  }
}

export function addSignatureSection(
  doc: jsPDF,
  y: number,
  facultyName: string = "Faculty",
  facultyDesig: string = "Faculty",
  hodName: string = "HOD",
  hodDesig: string = "Head of Department"
): void {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const colWidth = (pageWidth - margin * 2) / 2 - 5;

  if (y > 250) {
    doc.addPage();
    y = 30;
  }

  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.5);
  
  // Left column: Faculty
  const leftX = margin;
  const rightX = margin + colWidth + 10;
  
  // Faculty signature line - line at top, name/designation below
  doc.line(leftX, y, leftX + 50, y);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 30, 30);
  doc.text(`${facultyName}`, leftX, y + 8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(107, 114, 128);
  doc.setFontSize(8);
  doc.text(facultyDesig, leftX, y + 13);
  
  // HOD signature line - line at top, name/designation below
  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.5);
  doc.line(rightX, y, rightX + 50, y);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 30, 30);
  doc.text(hodName, rightX, y + 8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(107, 114, 128);
  doc.setFontSize(8);
  doc.text(hodDesig, rightX, y + 13);

  doc.setTextColor(0, 0, 0);
}

export function addSectionTitle(doc: jsPDF, title: string, y: number): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;

  doc.setFillColor(240, 244, 255);
  doc.rect(margin, y, pageWidth - margin * 2, 8, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(15, 37, 87);
  doc.text(title, margin + 3, y + 5.5);
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "normal");
  return y + 12;
}

export function tableOptions(startY: number) {
  return {
    startY,
    margin: { left: 15, right: 15 },
    headStyles: {
      fillColor: [15, 37, 87] as [number, number, number],
      textColor: [255, 255, 255] as [number, number, number],
      fontStyle: "bold" as const,
      fontSize: 9,
    },
    bodyStyles: {
      fontSize: 8,
      textColor: [30, 30, 30] as [number, number, number],
    },
    alternateRowStyles: {
      fillColor: [248, 249, 252] as [number, number, number],
    },
    tableLineColor: [229, 231, 235] as [number, number, number],
    tableLineWidth: 0.3,
  };
}

export { autoTable };
