import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { formatDate } from "./formatters";

interface ReportHeader {
  institutionName: string;
  reportTitle: string;
  generatedBy: string;
  departmentLabel?: string;
}

export function createPDF(header: ReportHeader): jsPDF {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;

  // Header bar
  doc.setFillColor(15, 37, 87);
  doc.rect(0, 0, pageWidth, 28, "F");

  // Institution name
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(header.institutionName, margin, 12);

  // Report title
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(header.reportTitle, margin, 20);

  // Date (right-aligned)
  const dateStr = formatDate(new Date());
  doc.text(dateStr, pageWidth - margin, 12, { align: "right" });

  if (header.departmentLabel) {
    doc.setFontSize(9);
    doc.text(header.departmentLabel, pageWidth - margin, 20, { align: "right" });
  }

  // Reset text color
  doc.setTextColor(0, 0, 0);
  doc.setDrawColor(232, 160, 32);
  doc.setLineWidth(1);
  doc.line(0, 28, pageWidth, 28);

  return doc;
}

export function addPageNumbers(doc: jsPDF): void {
  const pageCount = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(107, 114, 128);
    doc.text(
      `Page ${i} of ${pageCount}  |  Generated by IMS Portal`,
      pageWidth / 2,
      pageHeight - 8,
      { align: "center" }
    );
    doc.setDrawColor(229, 231, 235);
    doc.setLineWidth(0.3);
    doc.line(15, pageHeight - 12, pageWidth - 15, pageHeight - 12);
  }
}

export function addSignatureSection(doc: jsPDF, y: number): void {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;

  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.5);
  doc.line(margin, y + 20, margin + 60, y + 20);
  doc.setFontSize(9);
  doc.setTextColor(107, 114, 128);
  doc.text("HOD Signature", margin, y + 26);

  doc.line(pageWidth - margin - 60, y + 20, pageWidth - margin, y + 20);
  doc.text("Principal / Dean Signature", pageWidth - margin - 60, y + 26);
}

export function addSectionTitle(doc: jsPDF, title: string, y: number): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;

  doc.setFillColor(240, 244, 255);
  doc.rect(margin, y, pageWidth - margin * 2, 8, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(15, 37, 87);
  doc.text(title, margin + 3, y + 5.5);
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "normal");
  return y + 12;
}

export function tableOptions(startY: number) {
  return {
    startY,
    margin: { left: 15, right: 15 },
    headStyles: {
      fillColor: [15, 37, 87] as [number, number, number],
      textColor: [255, 255, 255] as [number, number, number],
      fontStyle: "bold" as const,
      fontSize: 9,
    },
    bodyStyles: {
      fontSize: 8,
      textColor: [30, 30, 30] as [number, number, number],
    },
    alternateRowStyles: {
      fillColor: [248, 249, 252] as [number, number, number],
    },
    tableLineColor: [229, 231, 235] as [number, number, number],
    tableLineWidth: 0.3,
  };
}

export { autoTable };
